import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import s03 from "../../docs/fixtures/s03-circular-arch/project.json";
import {
  DEFAULT_BEARING_PA,
  DEFAULT_DEPTH_M,
  DEFAULT_FROST_M,
  DEFAULT_MU_SOIL,
  STEP_ANGLE_DEG,
  footingMetrics,
  generateFootings,
  regenerateFootings,
} from "../../src/analysis/footings";
import { loadProject } from "../../src/persist/project";
import { Inspector } from "../../src/ui/Inspector";

describe("S10 — Auto footings and frost display", () => {
  it("stepped spread footing under every wall/pier/buttress that lacks one", () => {
    const project = generateFootings(loadProject(s03));
    const walls = project.faces.filter(
      (f) => f.regionKind === "masonryWall" || f.regionKind === "masonryPier",
    );
    const founds = project.faces.filter((f) => f.regionKind === "foundation");
    expect(founds.length).toBe(walls.length);
    expect(project.foundations?.every((f) => f.autoGenerated && !f.userEdited)).toBe(
      true,
    );
    expect(founds.every((f) => f.loop.length >= 3)).toBe(true);
  });

  it("auto-updates when H/loads/depth change unless userEdited", () => {
    const first = generateFootings(loadProject(s03));
    const id = first.foundations![0]!.id;
    const locked = {
      ...first,
      foundations: first.foundations!.map((f, i) =>
        i === 0 ? { ...f, userEdited: true } : f,
      ),
      faces: first.faces.map((f) =>
        f.id === id ? { ...f, userEdited: true } : f,
      ),
    };
    const before = locked.vertices.filter((v) => v.id.startsWith(`${id}-`));
    const updated = generateFootings({
      ...locked,
      foundationDepthDefault: 1.5,
    });
    const afterLocked = updated.vertices.filter((v) => v.id.startsWith(`${id}-`));
    expect(afterLocked).toEqual(before);
    const other = updated.foundations!.find((f) => f.id !== id)!;
    const otherBot = updated.vertices.find((v) => v.id === `${other.id}-v0`);
    expect(otherBot?.y).toBeCloseTo(-1.5, 6);
  });

  it("checks bearing, middle third, slide with soil μ, frost line vs depth", () => {
    const project = generateFootings(loadProject(s03));
    const metrics = footingMetrics(project);
    expect(metrics.soilPreset).toBe("stiff-clay-firm-sand");
    expect(metrics.allowableBearingPa).toBe(DEFAULT_BEARING_PA);
    expect(metrics.muSoil).toBe(DEFAULT_MU_SOIL);
    expect(metrics.defaultDepth_m).toBe(DEFAULT_DEPTH_M);
    expect(metrics.frostLineDepth_m).toBe(DEFAULT_FROST_M);
    expect(metrics.stepAngle_deg).toBe(STEP_ANGLE_DEG);
    expect(metrics.noRebar && metrics.noPiles && metrics.noGradeBeams).toBe(true);
    expect(metrics.noFrostHeave).toBe(true);
    expect(metrics.checks.length).toBeGreaterThan(0);
    expect(metrics.checks.every((c) => c.bearingOk)).toBe(true);
    expect(metrics.checks.every((c) => c.middleThirdOk)).toBe(true);
    expect(metrics.checks.every((c) => c.slideOk)).toBe(true);
    expect(metrics.checks.every((c) => c.frostOk)).toBe(true);
    expect(metrics.frostStatus).toBe("OK");
  });

  it("FROST_SHALLOW when depth < frost line; FOOTING_USER_EDITED when locked", () => {
    const shallow = generateFootings({
      ...loadProject(s03),
      foundationDepthDefault: 0.5,
    });
    const frost = footingMetrics(shallow);
    expect(frost.frostStatus).toBe("too shallow");
    expect(frost.warnings.some((w) => w.code === "FROST_SHALLOW")).toBe(true);
    const gen = generateFootings(loadProject(s03));
    const id = gen.foundations![0]!.id;
    const edited = footingMetrics({
      ...gen,
      foundations: gen.foundations!.map((f, i) =>
        i === 0 ? { ...f, userEdited: true } : f,
      ),
      faces: gen.faces.map((f) =>
        f.id === id ? { ...f, userEdited: true } : f,
      ),
    });
    expect(edited.warnings.some((w) => w.code === "FOOTING_USER_EDITED")).toBe(
      true,
    );
  });

  it("regenerate rebuilds non-edited, or all after confirm; inspector frost readout", () => {
    const gen = generateFootings(loadProject(s03));
    const id = gen.foundations![0]!.id;
    const locked = {
      ...gen,
      foundationDepthDefault: 1.5,
      foundations: gen.foundations!.map((f, i) =>
        i === 0 ? { ...f, userEdited: true } : f,
      ),
      faces: gen.faces.map((f) =>
        f.id === id ? { ...f, userEdited: true } : f,
      ),
    };
    const partial = regenerateFootings(locked, false);
    const lockedBot = partial.vertices.find((v) => v.id === `${id}-v0`);
    expect(lockedBot?.y).toBeCloseTo(-DEFAULT_DEPTH_M, 6);
    const all = regenerateFootings(locked, true);
    expect(
      all.vertices.find((v) => v.id.endsWith("-v0") && v.id.startsWith("found-"))
        ?.y,
    ).toBeCloseTo(-1.5, 6);
    const metrics = footingMetrics(gen);
    const html = renderToStaticMarkup(
      createElement(Inspector, {
        project: gen,
        error: null,
        leftover: null,
        footings: metrics,
        canUndo: false,
        canRedo: false,
        selectedEdgeId: "",
        typedLength: "",
        onUnits: () => undefined,
        onSave: () => undefined,
        onLoadFile: () => undefined,
        onUndo: () => undefined,
        onRedo: () => undefined,
        onAllowCutCourse: () => undefined,
        onSelectEdge: () => undefined,
        onTypedLength: () => undefined,
        onApplyLength: () => undefined,
      }),
    );
    expect(html).toContain("Frost line");
    expect(html).toContain("OK");
    expect(html).toContain("too shallow");
  });
});
