import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import s01 from "../../docs/fixtures/s01-one-wall/project.json";
import { coreCompare, coreMetrics } from "../../src/analysis/core";
import type { Project } from "../../src/model/project";
import { loadProject } from "../../src/persist/project";
import { Inspector } from "../../src/ui/Inspector";

function withCore(binder: "dry" | "lime-bound" = "dry"): Project {
  const project = loadProject(s01);
  project.vertices.push(
    { id: "vc0", x: 0.1016, y: 0 },
    { id: "vc1", x: 0.508, y: 0 },
    { id: "vc2", x: 0.508, y: 1.8288 },
    { id: "vc3", x: 0.1016, y: 1.8288 },
  );
  project.edges.push(
    { id: "ec0", kind: "line", start: "vc0", end: "vc1" },
    { id: "ec1", kind: "line", start: "vc1", end: "vc2" },
    { id: "ec2", kind: "line", start: "vc2", end: "vc3" },
    { id: "ec3", kind: "line", start: "vc3", end: "vc0" },
  );
  project.faces.push({
    id: "fCore",
    regionKind: "rubble",
    coreBinder: binder,
    loop: ["ec0", "ec1", "ec2", "ec3"],
  });
  return project;
}

describe("S12 — User-drawn cores (dry vs lime)", () => {
  it("solid until the user draws rubble; no auto core or skin", () => {
    const solid = coreMetrics(loadProject(s01));
    expect(solid.coreDrawn).toBe(false);
    expect(solid.autoGeneratedCore).toBe(false);
    expect(solid.autoGeneratedSkin).toBe(false);
    expect(solid.kernIsFullWall).toBe(true);
    expect(solid.kernWidth_m).toBeCloseTo(solid.wallThickness_m, 6);
    const drawn = coreMetrics(withCore("dry"));
    expect(drawn.coreDrawn).toBe(true);
    expect(drawn.autoGeneratedCore).toBe(false);
  });

  it("new core binder defaults dry; lime-bound is opt-in; joints stay independent", () => {
    const project = withCore();
    expect(project.coreBinderDefault).toBe("dry");
    expect(project.jointMode).toBe("lime");
    const metrics = coreMetrics(project);
    expect(metrics.binderDefault).toBe("dry");
    expect(metrics.binder).toBe("dry");
    expect(metrics.jointModeIndependent).toBe(true);
  });

  it("dry kern is skins only; lime-bound kern may use the full wall", () => {
    const dry = coreMetrics(withCore("dry"), "dry");
    const lime = coreMetrics(withCore("lime-bound"), "lime-bound");
    expect(dry.kernWidth_m).toBeLessThan(dry.wallThickness_m - 1e-6);
    expect(dry.kernIsFullWall).toBe(false);
    expect(lime.kernIsFullWall).toBe(true);
    expect(lime.kernWidth_m).toBeCloseTo(lime.wallThickness_m, 6);
    expect(dry.skinInner_m + dry.skinOuter_m).toBeCloseTo(dry.kernWidth_m, 6);
  });

  it("through-stones project into the core at bonding courses", () => {
    expect(coreMetrics(withCore("dry")).throughStonesProject).toBe(true);
  });

  it("switching only binder re-runs analysis; inspector A/B", () => {
    const project = withCore("dry");
    const ab = coreCompare(project);
    expect(ab.dry.kernWidth_m).not.toBeCloseTo(ab.limeBound.kernWidth_m, 4);
    expect(ab.limeBound.limeVolume_m3).toBeGreaterThan(ab.dry.limeVolume_m3);
    expect(ab.limeBound.costProxy).toBeGreaterThan(0);
    const html = renderToStaticMarkup(
      createElement(Inspector, {
        project,
        error: null,
        leftover: null,
        core: ab.dry,
        coreCompare: ab,
        canUndo: false,
        canRedo: false,
        selectedEdgeId: "",
        typedLength: "",
        onUnits: () => undefined,
        onSave: () => undefined,
        onLoadFile: () => undefined,
        onUndo: () => undefined,
        onRedo: () => undefined,
        onAllowCutCourse: () => undefined,
        onSelectEdge: () => undefined,
        onTypedLength: () => undefined,
        onApplyLength: () => undefined,
      }),
    );
    expect(html).toContain("Core binder");
    expect(html).toContain("A/B");
    expect(html).toContain("skins only");
  });
});
