/** Display-only (ADR-003). Stored numbers are SI. */
export type DisplayUnits = "us-customary" | "metric";

export type SliceZMode = "header-course" | "stretcher-course" | "custom";
export type BondPattern = "english" | "flemish" | "common" | "ashlar-through";
export type WallConstruction = "solid" | "skins-and-core";
export type JointMode = "dry" | "lime";
export type SoilPreset =
  | "soft-clay"
  | "stiff-clay-firm-sand"
  | "dense-sand-gravel"
  | "bedrock";
export type RiseCapMode =
  | "percent-sagitta"
  | "percent-span"
  | "sagitta-plus-span"
  | "semicircle"
  | "deck-only"
  | "shape-only";
export type ButtressFaceMode = "vertical" | "taper" | "tiered";
export type CoreBinder = "dry" | "lime-bound";
export type RingOrientation =
  | "rowlock-header"
  | "on-edge"
  | "bed"
  | "stretcher-barrel"
  | "ashlar";

export interface Vertex {
  id: string;
  x: number;
  y: number;
}

export type EdgeKind = "line" | "arch";
export type ArchFamily = "circular" | "funicular";
export type EdgeConstraint =
  | "horizontal"
  | "vertical"
  | "perpendicular"
  | "equal-length";

export interface Edge {
  id: string;
  kind: EdgeKind;
  start: string;
  end: string;
  archFamily?: ArchFamily;
  rise?: number;
  constraints?: EdgeConstraint[];
}

export type RegionKind =
  | "void"
  | "archOpening"
  | "archRing"
  | "masonryWall"
  | "masonryPier"
  | "fill"
  | "rubble"
  | "deck"
  | "buttress"
  | "foundation"
  | "centering";

export interface Face {
  id: string;
  regionKind: RegionKind;
  loop: string[];
  materialId?: string;
  lockedThickness?: boolean;
  ringThickness?: number;
  leftoverHeight?: number;
  coreBinder?: CoreBinder;
  skinThicknessWythes?: number;
  unitCatalogId?: string;
  userEdited?: boolean;
  units3D?: unknown[];
  stones2D?: unknown[];
}

export type LoadCaseKind =
  | "dead-only"
  | "dead-plus-uniform-live"
  | "dead-plus-asymmetric-live";

export interface PatchLoad {
  x: number;
  width: number;
  forceN: number;
}

export interface LoadCase {
  id: string;
  kind: LoadCaseKind;
  livePreset?: "dwelling" | "crowd" | "roof-snow" | "custom";
  uniformLivePa?: number;
  patchLoads?: PatchLoad[];
}

export interface Material {
  id: string;
  density: number;
  name?: string;
  mu?: number;
  cohesion?: number;
  allowableCompression?: number;
}

export interface ArchMember {
  id: string;
  color?: string;
  faceId?: string;
  t?: number;
  N?: number;
  orientation?: string;
  Nv?: number;
  vaultBond?: "rowlock-rings" | "stretcher-barrel" | "ashlar-ring";
  r0?: number;
  rOpt?: number;
}

export interface Foundation {
  id: string;
  autoGenerated: boolean;
  userEdited: boolean;
  faceId?: string;
  bearing?: number;
  resultantOffset?: number;
  spreadRisk?: boolean;
}

export interface Warning {
  code: string;
  severity: "info" | "amber" | "red";
  message: string;
  targetId?: string;
}

/** Field names frozen in project.schema.json (ADR-003). */
export interface Project {
  requirementsVersion: "1.4";
  units: DisplayUnits;
  sliceDepth: number;
  vertices: Vertex[];
  edges: Edge[];
  faces: Face[];
  g?: number;
  sliceZMode?: SliceZMode;
  sliceZ?: number;
  bondPattern?: BondPattern;
  wallConstruction?: WallConstruction;
  jointMode?: JointMode;
  loadFactorsOn?: boolean;
  soilPreset?: SoilPreset;
  frostLineDepth?: number;
  foundationDepthDefault?: number;
  riseCapMode?: RiseCapMode;
  riseCapPercent?: number;
  buttressFaceMode?: ButtressFaceMode;
  coreBinderDefault?: CoreBinder;
  unitCatalogId?: string;
  orientations?: { ring?: RingOrientation };
  allowCutCourse?: boolean;
  wholeUnitsOnly?: boolean;
  loadCases?: LoadCase[];
  materials?: Material[];
  archMembers?: ArchMember[];
  foundations?: Foundation[];
  warnings?: Warning[];
}
