import {
  inchesToMetres,
  stretcherWythePitchIn,
} from "../catalog/brick";
import { faceBounds } from "../geom/graph";
import type { CoreBinder, Face, Project } from "../model/project";
import { generateMasonry } from "../masonry/generate";

export const LIME_MIX_LIME_FRACTION = 0.25;
export const DEFAULT_LIME_UNIT_PRICE = 1;

export type CoreMetrics = {
  coreDrawn: boolean;
  autoGeneratedCore: false;
  autoGeneratedSkin: false;
  binderDefault: "dry";
  binder: CoreBinder;
  jointModeIndependent: true;
  wallThickness_m: number;
  coreWidth_m: number;
  skinInner_m: number;
  skinOuter_m: number;
  skinSnapWythe_m: number;
  skinLeftover_m: number;
  kernWidth_m: number;
  kernIsFullWall: boolean;
  throughStonesProject: boolean;
  limeVolume_m3: number;
  costProxy: number;
};

function rubbleFaces(project: Project): Face[] {
  return project.faces.filter((f) => f.regionKind === "rubble");
}

function snapToWythe(width: number, pitch: number): {
  snapped: number;
  leftover: number;
} {
  if (pitch <= 0) return { snapped: width, leftover: 0 };
  const n = Math.max(1, Math.round(width / pitch));
  const snapped = n * pitch;
  return { snapped, leftover: width - snapped };
}

export function coreMetrics(
  project: Project,
  binderOverride?: CoreBinder,
): CoreMetrics {
  const walls = project.faces.filter((f) => f.regionKind === "masonryWall");
  const wall = walls[0];
  const wallB = wall ? faceBounds(project, wall) : null;
  const wallThickness_m = wallB ? wallB.maxX - wallB.minX : 0;
  const cores = rubbleFaces(project);
  const coreDrawn = cores.length > 0;
  const binder: CoreBinder =
    binderOverride ??
    cores[0]?.coreBinder ??
    project.coreBinderDefault ??
    "dry";
  const pitch = inchesToMetres(
    stretcherWythePitchIn(project.unitCatalogId, project.jointMode),
  );
  let coreWidth_m = 0;
  let skinInner_m = wallThickness_m;
  let skinOuter_m = 0;
  if (coreDrawn && wallB) {
    const cb = faceBounds(project, cores[0]!);
    coreWidth_m = cb.maxX - cb.minX;
    skinOuter_m = Math.max(0, cb.minX - wallB.minX);
    skinInner_m = Math.max(0, wallB.maxX - cb.maxX);
  }
  const innerSnap = snapToWythe(skinInner_m, pitch);
  const outerSnap = snapToWythe(skinOuter_m, pitch);
  const kernIsFullWall = !coreDrawn || binder === "lime-bound";
  const kernWidth_m = kernIsFullWall
    ? wallThickness_m
    : innerSnap.snapped + outerSnap.snapped;
  const coreArea = coreDrawn && wallB
    ? coreWidth_m * (wallB.maxY - wallB.minY)
    : 0;
  const limeVolume_m3 =
    binder === "lime-bound" ? coreArea * project.sliceDepth * LIME_MIX_LIME_FRACTION : 0;
  let throughStonesProject = false;
  if (coreDrawn && wall) {
    try {
      const masonry = generateMasonry(project, wall);
      const cb = faceBounds(project, cores[0]!);
      throughStonesProject = masonry.units3D.some(
        (u) =>
          (u.role === "header" || u.role === "through") &&
          u.minX < cb.maxX - 1e-9 &&
          u.maxX > cb.minX + 1e-9,
      );
    } catch {
      throughStonesProject = false;
    }
  }
  return {
    coreDrawn,
    autoGeneratedCore: false,
    autoGeneratedSkin: false,
    binderDefault: "dry",
    binder,
    jointModeIndependent: true,
    wallThickness_m,
    coreWidth_m,
    skinInner_m: innerSnap.snapped,
    skinOuter_m: outerSnap.snapped,
    skinSnapWythe_m: pitch,
    skinLeftover_m: innerSnap.leftover + outerSnap.leftover,
    kernWidth_m,
    kernIsFullWall,
    throughStonesProject,
    limeVolume_m3,
    costProxy: limeVolume_m3 * DEFAULT_LIME_UNIT_PRICE,
  };
}

export function coreCompare(project: Project): {
  dry: CoreMetrics;
  limeBound: CoreMetrics;
} {
  return {
    dry: coreMetrics(project, "dry"),
    limeBound: coreMetrics(project, "lime-bound"),
  };
}
